
TYPE
	ShowModules : 
		(
		CONFIGURED_MODULES := 2,
		ALL := 3,
		PLUGGED := 1
		);
	ModuleInfo : 
		(
		EPLAN_MODULE_TAG := 1007,
		HW_MODULE_NAME := 1006,
		PLUGGED_MODULE_BUS := 1004,
		CONFIGURATED_MODULE_BUS := 1005,
		PLUGGED_MODULE_NAME := 1002,
		CONFIG_MODULE_NAME := 1003,
		MODULE_PATH := 1001
		);
END_TYPE
